### ISSUE TITLE
e09 - Missing test files

### ISSUE THREAD

**Issue by LadnerJonas** [MaximilianAnzinger/gad2022-tests#32]
@WoodyLetsCode 
Where can these test files be found?
For example:
https://github.com/MaximilianAnzinger/gad2022-tests/blob/5285c66799a883feefdc3497a71ba8fd7a68169a/e09-avl-tree/src/tests/testInsert.java#L35

**Comment by WoodyLetsCode** [comment]
Sorry! I forgot to push these files. Give me a moment.
