### ISSUE TITLE
Tree 6 expected value probably wrong

### ISSUE THREAD

**Issue by fabianscode** [MaximilianAnzinger/gad2022-tests#41]
https://github.com/MaximilianAnzinger/gad2022-tests/commit/ea1337f221bdaa348e4efff12fbdb9697a915924

I'm not sure why this was changed, but it was probably correct before the change... since all children of the minNode have to be moved into the root list, **before** calling consolidate(), all nodes should be part of the root list

**Comment by WoodyLetsCode** [comment]
@V1leDev

**Comment by MaximilianAnzinger** [comment]
I'm not allowed to create/edit tests, BUT: @fabianscode explanation is correct. Basically, the original heap (excl. the tree with root-min) has to be merged with the heap of the removed node (the children of min form a new FiboHeap). Consolidate should be performed after this step.

**Comment by V1leDev** [comment]
Created pull request to undo fix.
