### ISSUE TITLE
Fibonacci-Heap: Consolidate tests extractMin

### ISSUE THREAD

**Issue by SilicDev** [MaximilianAnzinger/gad2022-tests#44]
The test method for consolidate `FiboHeapConsolidateTest.consolidateTester()` calls extractMin instead of calling consolidate directly. This causes the test to be heavily dependant on extractMin without needing to. (Also means extractMin has to pass first, and I believe there might be a bug aswell as #41 mentions. ~~(Further the "dependency" on consolidate in FiboHeapExtractMinTest may be handled with an EasyMock mock instead)~~ Scratch that more complicated than I thought

**Comment by SilicDev** [comment]
I understand now why it was done that way, but I'd like to add that the designers of the exercise didn't need to make consolidate protected, this only makes testing harder.

**Comment by MaximilianAnzinger** [comment]
consolidate is a method that should not be available to end-users. Therefore, it would even be better if consolidate was private. However, mocking students implementations is significantly easier using the protected access modifier.
